# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adria/projects/gameEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adria/projects/gameEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adria/projects/gameEngine/CMakeFiles /home/adria/projects/gameEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adria/projects/gameEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameEngine

# Build rule for target.
gameEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gameEngine
.PHONY : gameEngine

# fast build rule for target.
gameEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/build
.PHONY : gameEngine/fast

exercises.o: exercises.cpp.o
.PHONY : exercises.o

# target to build an object file
exercises.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/exercises.cpp.o
.PHONY : exercises.cpp.o

exercises.i: exercises.cpp.i
.PHONY : exercises.i

# target to preprocess a source file
exercises.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/exercises.cpp.i
.PHONY : exercises.cpp.i

exercises.s: exercises.cpp.s
.PHONY : exercises.s

# target to generate assembly for a file
exercises.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/exercises.cpp.s
.PHONY : exercises.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/glad.c.s
.PHONY : glad.c.s

libraries/include/camera/camera.o: libraries/include/camera/camera.cpp.o
.PHONY : libraries/include/camera/camera.o

# target to build an object file
libraries/include/camera/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/camera/camera.cpp.o
.PHONY : libraries/include/camera/camera.cpp.o

libraries/include/camera/camera.i: libraries/include/camera/camera.cpp.i
.PHONY : libraries/include/camera/camera.i

# target to preprocess a source file
libraries/include/camera/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/camera/camera.cpp.i
.PHONY : libraries/include/camera/camera.cpp.i

libraries/include/camera/camera.s: libraries/include/camera/camera.cpp.s
.PHONY : libraries/include/camera/camera.s

# target to generate assembly for a file
libraries/include/camera/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/camera/camera.cpp.s
.PHONY : libraries/include/camera/camera.cpp.s

libraries/include/mesh/mesh.o: libraries/include/mesh/mesh.cpp.o
.PHONY : libraries/include/mesh/mesh.o

# target to build an object file
libraries/include/mesh/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/mesh/mesh.cpp.o
.PHONY : libraries/include/mesh/mesh.cpp.o

libraries/include/mesh/mesh.i: libraries/include/mesh/mesh.cpp.i
.PHONY : libraries/include/mesh/mesh.i

# target to preprocess a source file
libraries/include/mesh/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/mesh/mesh.cpp.i
.PHONY : libraries/include/mesh/mesh.cpp.i

libraries/include/mesh/mesh.s: libraries/include/mesh/mesh.cpp.s
.PHONY : libraries/include/mesh/mesh.s

# target to generate assembly for a file
libraries/include/mesh/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/mesh/mesh.cpp.s
.PHONY : libraries/include/mesh/mesh.cpp.s

libraries/include/render/render.o: libraries/include/render/render.cpp.o
.PHONY : libraries/include/render/render.o

# target to build an object file
libraries/include/render/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/render/render.cpp.o
.PHONY : libraries/include/render/render.cpp.o

libraries/include/render/render.i: libraries/include/render/render.cpp.i
.PHONY : libraries/include/render/render.i

# target to preprocess a source file
libraries/include/render/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/render/render.cpp.i
.PHONY : libraries/include/render/render.cpp.i

libraries/include/render/render.s: libraries/include/render/render.cpp.s
.PHONY : libraries/include/render/render.s

# target to generate assembly for a file
libraries/include/render/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/render/render.cpp.s
.PHONY : libraries/include/render/render.cpp.s

libraries/include/shader/shader.o: libraries/include/shader/shader.cpp.o
.PHONY : libraries/include/shader/shader.o

# target to build an object file
libraries/include/shader/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/shader/shader.cpp.o
.PHONY : libraries/include/shader/shader.cpp.o

libraries/include/shader/shader.i: libraries/include/shader/shader.cpp.i
.PHONY : libraries/include/shader/shader.i

# target to preprocess a source file
libraries/include/shader/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/shader/shader.cpp.i
.PHONY : libraries/include/shader/shader.cpp.i

libraries/include/shader/shader.s: libraries/include/shader/shader.cpp.s
.PHONY : libraries/include/shader/shader.s

# target to generate assembly for a file
libraries/include/shader/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/shader/shader.cpp.s
.PHONY : libraries/include/shader/shader.cpp.s

libraries/include/texture/texture.o: libraries/include/texture/texture.cpp.o
.PHONY : libraries/include/texture/texture.o

# target to build an object file
libraries/include/texture/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/texture/texture.cpp.o
.PHONY : libraries/include/texture/texture.cpp.o

libraries/include/texture/texture.i: libraries/include/texture/texture.cpp.i
.PHONY : libraries/include/texture/texture.i

# target to preprocess a source file
libraries/include/texture/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/texture/texture.cpp.i
.PHONY : libraries/include/texture/texture.cpp.i

libraries/include/texture/texture.s: libraries/include/texture/texture.cpp.s
.PHONY : libraries/include/texture/texture.s

# target to generate assembly for a file
libraries/include/texture/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/libraries/include/texture/texture.cpp.s
.PHONY : libraries/include/texture/texture.cpp.s

stb_image.o: stb_image.cpp.o
.PHONY : stb_image.o

# target to build an object file
stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/stb_image.cpp.o
.PHONY : stb_image.cpp.o

stb_image.i: stb_image.cpp.i
.PHONY : stb_image.i

# target to preprocess a source file
stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/stb_image.cpp.i
.PHONY : stb_image.cpp.i

stb_image.s: stb_image.cpp.s
.PHONY : stb_image.s

# target to generate assembly for a file
stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameEngine.dir/build.make CMakeFiles/gameEngine.dir/stb_image.cpp.s
.PHONY : stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gameEngine"
	@echo "... exercises.o"
	@echo "... exercises.i"
	@echo "... exercises.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... libraries/include/camera/camera.o"
	@echo "... libraries/include/camera/camera.i"
	@echo "... libraries/include/camera/camera.s"
	@echo "... libraries/include/mesh/mesh.o"
	@echo "... libraries/include/mesh/mesh.i"
	@echo "... libraries/include/mesh/mesh.s"
	@echo "... libraries/include/render/render.o"
	@echo "... libraries/include/render/render.i"
	@echo "... libraries/include/render/render.s"
	@echo "... libraries/include/shader/shader.o"
	@echo "... libraries/include/shader/shader.i"
	@echo "... libraries/include/shader/shader.s"
	@echo "... libraries/include/texture/texture.o"
	@echo "... libraries/include/texture/texture.i"
	@echo "... libraries/include/texture/texture.s"
	@echo "... stb_image.o"
	@echo "... stb_image.i"
	@echo "... stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

